dist: bionic
language: python

notifications:
  email: false

sudo: required

services:
  - docker

script:
  - env | grep DOCKER
  - echo "$DOCKER_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - VERSION=$(git rev-parse --short HEAD)
  - make -C notebook build
  - docker run -p 8888:8888 digiklausur/notebook:$VERSION
  - make -C restricted-notebook build
  - docker run -p 8889:8888 digiklausur/restricted-notebook:$VERSION
  - docker ps -a
  #- make push
  #- docker build -t digiklausur/notebook:1.0.0 ./images/notebook
