dist: focal
language: python

notifications:
  email: false

services:
  - docker

jobs:
  include:
    - stage: build-dev
      install:
      - bash .travis/build-dev.sh
    - stage: deploy-dev
      install:
      - bash .travis/deploy-dev.sh
    - stage: deploy-prod
      install:
      - bash .travis/deploy-prod.sh

stages:
  - name: build-dev
    if: type = pull_request AND branch = dev
  - name: deploy-dev
    if: type = pull_request AND branch = dev
  - name: build-prod
    if: type = pull_request AND branch = master

script:
  - docker images
