dist: focal
language: python

notifications:
  email: false

services:
  - docker

jobs:
  include:
    - stage: build-dev
      script:
      - bash .travis/build-dev.sh
    - stage: deploy-dev
      script:
      - bash .travis/deploy-dev.sh
    - stage: deploy-prod
      script:
      - bash .travis/deploy-prod.sh

stages:
  - name: build-dev
    if: type = pull_request
  - name: deploy-dev
    if: type = push AND branch = dev
  - name: deploy-prod
    if: type = push AND branch = master

