dist: bionic
language: python

notifications:
  email: false

sudo: required

services:
  - docker

script:
  - env | grep DOCKER
  - echo "$DOCKER_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - VERSION=$(git rev-parse --short HEAD)
    #- make -C minimal-notebook build
    #- make push -C minimal-notebook push
  - make -C notebook-dev build
  - make push -C notebook-dev push
  - make -C restricted-notebook-dev build
  - make push -C restricted-notebook-dev push
    #- docker run -it --rm -d -p 8882:8888 digiklausur/minimal-notebook:latest
  - docker run -it --rm -d -p 8881:8888 digiklausur/notebook-dev:$VERSION
  - docker run -it --rm -d -p 8881:8888 digiklausur/restricted-notebook-dev:$VERSION
  - docker ps -a
