dist: focal
language: python

notifications:
  email: false

services:
  - docker

script:
  - echo "Travis branch: $TRAVIS_BRANCH"
  - echo "Travis PR: $TRAVIS_PULL_REQUEST"
  - if [ "$TRAVIS_BRANCH" == "dev" ] && [ "$TRAVIS_PULL_REQUEST" == "true" ]; then
      bash .travis/build-dev.sh;
    fi
  - if [ "$TRAVIS_BRANCH" == "dev" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      bash .travis/deploy-dev.sh;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
      bash .travis/deploy-prod.sh;
    fi
