language: generic

notifications:
  email: false

sudo: required

services:
  - docker

before_install:
  - docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_TOKEN
  - VERSION=$(git rev-parse --short HEAD)
  - cd ./images/notebook
  - make build
  - docker run -p 8888:8888 digiklausur/notebook:$VERSION
  - docker ps -a
  - make push
  #- docker build -t digiklausur/notebook:1.0.0 ./images/notebook
