dist: bionic
language: python

notifications:
  email: false

sudo: required

services:
  - docker

script:
  - env | grep DOCKER
  - echo "$DOCKER_TOKEN" | docker login --username "$DOCKER_USERNAME" --password-stdin
  - VERSION=$(git rev-parse --short HEAD)
  - make -C notebook build
  - make -C restricted-notebook build
  - docker run -p 8888:8888 digiklausur/notebook:latest
  - docker run -p 8889:8888 digiklausur/restricted-notebook:latest
  - docker ps -a
  - make push -C notebook push
  - make push -C restricted-notebook push
