---
name: CI to ghcr.io
on:
  pull_request:
  push:
    branches:
      - master
      - dev
  schedule:
    - cron: "0 1 * * 0" # every 01.00 week 0 (sunday)

jobs:
  # Build image
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image
      id: docker_build
      run: |
        bash .github/scripts/build-and-deploy.sh --regisrty ghcr.io

    - name: Docker image list
      run: docker images

  deploy-dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
      #beta, need PAT
      #- name: Log into github registry
      #run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Build and deploy image
      id: docker_deploy_dev
      run: |
        # GitHub container registry is still beta, just build
        #bash .github/scripts/build-and-deploy.sh --deployment dev --registry ghcr.io
        bash .github/scripts/build-and-deploy.sh --registry ghcr.io

    - name: Docker image list
      run: docker images

  deploy-prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    #beta, need PAT
    #- name: Log into github registry
      #run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin

    - name: Build and deploy image
      id: docker_deploy_prod
      run: |
        # GitHub container registry is still beta, just build
        #bash .github/scripts/build-and-deploy.sh --deployment prod --registry ghcr.io
        bash .github/scripts/build-and-deploy.sh --registy ghcr.io

    - name: Docker image list
      run: docker images
