---
name: CI to ghcr.io
on:
  pull_request:
  push:
    branches:
      - master
      - dev
  schedule:
    - cron: "0 1 * * 0" # every 01.00 week 0 (sunday)

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image
      id: docker_build
      run: |
        bash .github/scripts/build-and-deploy.sh --deployment "" --registry ghcr.io

    - name: Docker image list
      run: docker images

  deploy-dev:
    name: Deploy Dev
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/dev'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log into github registry
      run: echo $GH_TOKEN | docker login ghcr.io -u $GH_USERNAME --password-stdin

    - name: Build and deploy image
      id: docker_deploy_dev
      run: |
        # GitHub container registry is still beta
        bash .github/scripts/build-and-deploy.sh --deployment dev --registry ghcr.io --publish latest

    - name: Docker image list
      run: docker images

  deploy-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Log into github registry
      run: echo $GH_TOKEN | docker login ghcr.io -u $GH_USERNAME --password-stdin

    - name: Build and deploy image
      id: docker_deploy_prod
      run: |
        # GitHub container registry is still beta, just build
        bash .github/scripts/build-and-deploy.sh --deployment prod --registry ghcr.io --publish latest

    - name: Docker image list
      run: docker images
