---
name: Build CI to Docker Hub
on:
  pull_request:
  push:
    branches:
      - master
      - dev
  schedule:
    - cron: "0 1 * * 0" # every 01.00 week 0 (sunday)

defaults:
  run:
    working-directory: 'digiklausur.docker-stack'

jobs:
  # Build image
  build:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build image
      id: docker_build
      run: |
        ls -al
        bash .travis/build-dev.sh

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  deploy-dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'ref/head/dev'

    steps:
    - uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and deploy image
      id: docker_deploy_dev
      run: |
        ls -al
        bash .travis/deploy-dev.sh

    - name: Image digest
      run: echo ${{ steps.docker_deploy_dev.outputs.digest }}

